// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have over five hundred divisors?

var triangleNum = function(num){
  var sum = 0;

  for(var counter = num; counter > 0; counter--){
    sum += counter;
  }

  return sum;
};

var theFactorsOf = function(num) {
  var factors = [];

  for (var counter = 1; counter < num; counter++) {
    if (num % counter === 0) {
      factors.push(counter);
    }
  }

  return factors;
};

var divisorsNum = function(num){
  var nth_tri_num = 0;

  for(var counter = 1; theFactorsOf(triangleNum(counter)).length <= num; counter++){
    if (counter > nth_tri_num){
      nth_tri_num = counter;
    }
  }

  return triangleNum(nth_tri_num);
};

divisorsNum(500);
